CATEGORIES = ['Animals & Wildlife: Species, habitats, behaviors.',
              'Countries & Geography: Capitals, landmarks, physical features.',
              'Historical Figures & Events: Leaders, inventors, pivotal moments.',
              'Food & Cuisine: Dishes, ingredients, cooking techniques.',
              'Sports & Games: Athletes, rules, famous competitions.',
              'Movies & Television: Actors, genres, classic films.',
              'Literature & Books: Authors, literary terms, classic novels.',
              'Science & Nature: Elements, laws of physics, plants.',
              'Technology & Gadgets: Innovations, inventors, brand names.',
              'Music & Musicians: Bands, song titles, instruments.',
              'Art & Artists: Movements, techniques, famous works.',
              'Famous Landmarks: Monuments, natural wonders, historical sites.',
              'Occupations & Professions: Job titles, work environments, duties.',
              'Mythology & Folklore: Gods, mythical creatures, legends.',
              'Vehicles & Transportation: Car models, parts, historical milestones.',
              'Languages & Dialects: Phrases, language families, characteristics.',
              'Fashion & Brands: Designers, trends, iconic products.', 'Plants & Flowers: Species, parts, uses.',
              'Board Games & Puzzles: Game mechanics, classic games, strategies.',
              'Astronomy & Space: Planets, space missions, celestial phenomena.',
              'Hobbies & Crafts: Techniques, materials, project types.',
              'Health & Medicine: Diseases, treatments, body parts.',
              'Physics & Chemistry: Phenomena, compounds, principles.',
              'Mathematics & Numbers: Equations, concepts, famous mathematicians.',
              'Comics & Superheroes: Characters, creators, story arcs.',
              'Philosophy & Ideas: Philosophers, concepts, schools of thought.',
              'Religions & Beliefs: Deities, rituals, sacred texts.', 'Video Games: Titles, characters, developers.',
              'Environmental Issues: Conservation, phenomena, movements.',
              'Celebrities & Public Figures: Influencers, philanthropists, scandals.']

