INTRO = """# 🌟 Welcome to WhichAsk-Guess: A Mystery Game! 🌟

---

## 🎩 **Overview:**
In WhichAsk-Guess, players embark on a journey of deduction and collaboration. One player takes on the role of the **Questioner**, while the other becomes the **Answerer**.

---

## 🧠 **Gameplay Mechanics:**
- The **Answerer** is entrusted with a secret word unknown to the **Questioner**.
- Each round, the **Questioner** can pose one question to the **Answerer**, who must respond truthfully without revealing the secret word or phrase.
- Together, players work to minimize the number of rounds needed for the **Questioner** to accurately deduce the hidden word.
- The **Questioner's** strategy is crucial, as targeted questions will progressively narrow down the potential options based on the **Answerer's** responses.
- Once the **Questioner** believes they've identified the word, the **Answerer** will confirm by responding with 'Gameover', marking the end of the game.

---

## 💡 **Objective:**
Put your deduction skills to the test and collaborate closely to unravel the mystery!

---

## 🚀 **Let the WhichAsk-Guess adventure begin!**

"""
RULES = """
---

## 🔍 **Objective:**
It's all about guessing! The questioner's mission is to crack the code and guess the secret word or phrase hidden by the answerer. 🤔

---

## 🗣️ **Questioning:**
Ask away! The questioner fires questions at the answerer to unravel the mystery. 💬

---

## 🤫 **Answering:**
Keep it real! The answerer must respond truthfully, dropping hints and clues without spilling the beans on the secret word or phrase. 💡

---

## 🏁 **End of Game:**
Victory dance! When the questioner finally cracks the code, the answerer shouts "gameover" to celebrate the win! 🎉

---

## 🕺 **Avoiding Direct Mentions:**
No spoilers allowed! The answerer must dance around the secret word or phrase, giving clever hints without giving it away. 💬

---

## 🤐 **Maintaining Secrecy:**
Shhh... The answerer must keep their sources hidden, answering solely based on the questions asked without revealing any secrets. 🔒

---

## 🍎 **Example:**
Let's get fruity! If the secret word is "apple", the answerer can drop hints about its color, taste, or where it grows, but without saying "apple" directly! 🌳
"""

LLM_VS_LLM = """
# 🤖 Welcome to LLM vs LLM: The AI Showdown Game!

---

## 🎮 Game Overview:
LLM vs LLM is a thrilling game where two AI models battle head-to-head. One AI acts as the **Answerer**, generating a password based on a chosen category, while the other AI takes on the role of the **Questioner**, attempting to guess the password through strategic questioning. 

---

## 🔍 Objective:
The Questioner's mission is to deduce the password generated by the Answerer by asking insightful questions. The game concludes when the Questioner successfully guesses the password or when the Questioner exhausts all their questions.

---

## 💡 Gameplay Mechanics:
- **Answerer Role**: Generates a password based on a chosen category.
- **Questioner Role**: Asks questions to uncover the password.
- **Category Selection**: Determines the theme of the password.
- **Question Limit**: The Questioner has a limited number of questions to guess the password.

---

## 🤖 AI Showdown:
Witness the ultimate battle of wit and intelligence as two AI models face off in a battle of strategy and deduction. Who will emerge victorious, the Answerer with its cunningly crafted password or the Questioner with its sharp questioning skills?

---

## 🚀 Let the LLM vs LLM showdown begin! Are you ready to witness the clash of AI titans?

    
"""